/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi_Amplang;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author User
 */
public class CRUDform extends javax.swing.JFrame {

    /**
     * Creates new form CRUDform
     */
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    
    public CRUDform() {
        initComponents();
        table();
    }
    
    private void table(){
        DefaultTableModel tbl  = (DefaultTableModel) tabelAmplang.getModel();
        tabelAmplang.setRowHeight(40);
        tabelAmplang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabelAmplang.getColumnModel().getColumn(0).setPreferredWidth(60);
        tabelAmplang.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelAmplang.getColumnModel().getColumn(0).setMinWidth(0);
        tbl.setRowCount(0);        
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaplikasiamplang", "root", "");
            // membuat statement dan mengirimkan query ke database
            String sql = "SELECT * FROM tbamplang";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            // mengisi data dari ResultSet ke dalam model
            while(rs.next()) {
                String no = Integer.toString(rs.getInt("no"));
                String namaAmplang = rs.getString("nama");
                String jenis = rs.getString("jenis");
                String ukuran = rs.getString("ukuran");
                String jumlah = rs.getString("jumlah");
                String harga = Double.toString(rs.getDouble("harga"));
                tbl.addRow(new Object []{no, namaAmplang, jenis, ukuran, jumlah, harga});
                tabelAmplang.setModel(tbl);
            }
            conn.close();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAmplang = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbUkuran = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CRUD App Amplang");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Form CRUD Amplang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama Amplang");

        tabelAmplang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Jenis Ikan", "Ukuran", "Jumlah", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelAmplang.setShowGrid(true);
        tabelAmplang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAmplangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAmplang);
        if (tabelAmplang.getColumnModel().getColumnCount() > 0) {
            tabelAmplang.getColumnModel().getColumn(0).setResizable(false);
            tabelAmplang.getColumnModel().getColumn(1).setResizable(false);
            tabelAmplang.getColumnModel().getColumn(2).setResizable(false);
            tabelAmplang.getColumnModel().getColumn(3).setResizable(false);
            tabelAmplang.getColumnModel().getColumn(4).setResizable(false);
            tabelAmplang.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Jenis Ikan");

        cbUkuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "40 Gram", "80 Gram", "120 Gram", "160 Gram", "200 Gram" }));
        cbUkuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUkuranActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Harga");

        btnTambah.setBackground(new java.awt.Color(102, 204, 255));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 255, 0));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCariMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tabel Daftar Amplang");

        jRadioButton1.setText("Tenggiri");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Jumlah");

        jRadioButton2.setText("Haruan");

        jRadioButton3.setText("Belida");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Ukuran");

        btnCari.setBackground(new java.awt.Color(102, 204, 255));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Search");
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCariMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2)
                                        .addGap(36, 36, 36)
                                        .addComponent(jRadioButton3))
                                    .addComponent(cbUkuran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJumlah)
                                    .addComponent(txtHarga)
                                    .addComponent(jLabel8)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(73, 73, 73)
                                .addComponent(btnCari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelAmplangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAmplangMouseClicked
        int baris = tabelAmplang.getSelectedRow();
        txtNama.setText(tabelAmplang.getValueAt(baris,1).toString());
//        jRadioButton1.setText(tabelAmplang.getValueAt(baris,2).toString());
//        jRadioButton2.setText(tabelAmplang.getValueAt(baris,2).toString());
//        jRadioButton3.setText(tabelAmplang.getValueAt(baris,2).toString());
        cbUkuran.setSelectedItem(tabelAmplang.getValueAt(baris,3).toString());
        txtJumlah.setText(tabelAmplang.getValueAt(baris,4).toString());
        txtHarga.setText(tabelAmplang.getValueAt(baris,5).toString());
    }//GEN-LAST:event_tabelAmplangMouseClicked

    private void cbUkuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUkuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUkuranActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaplikasiamplang", "root", "");
            String sql = "insert into tbamplang (nama, jenis, ukuran, jumlah, harga) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, txtNama.getText());
            String jenis = "";
            boolean isValidSelection = false;
            if (jRadioButton1.isSelected()) {
                jenis = "Tenggiri";
                isValidSelection = true;
            } else if (jRadioButton2.isSelected()) {
                jenis = "Haruan";
                isValidSelection = true;
            } else if (jRadioButton3.isSelected()) {
                jenis = "Belida";
                isValidSelection = true;
            } else {
                JOptionPane.showMessageDialog(this,
                    "jenis tidak valid, pilih jenis!",
                    "Gagal", JOptionPane.ERROR_MESSAGE);
            }
            stmt.setString(2, jenis);
            stmt.setString(3, cbUkuran.getSelectedItem().toString());
            stmt.setInt(4, Integer.parseInt(txtJumlah.getText()));
            stmt.setDouble(5, Double.parseDouble(txtHarga.getText()));

            int masukan_row = stmt.executeUpdate();

            if(masukan_row > 0){
                JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!!!");
                txtNama.setText("");
                jRadioButton1.setSelected(false);
                jRadioButton2.setSelected(false);
                jRadioButton3.setSelected(false);
                cbUkuran.setSelectedIndex(-1);
                txtJumlah.setText("");
                txtHarga.setText("");
                table();
            }
            conn.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Data gak bisa masuk!!! terjadi error:" + ex.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int baris = tabelAmplang.getSelectedRow();
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaplikasiamplang", "root", "");
            int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                String sql = "DELETE FROM tbamplang WHERE no=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, tabelAmplang.getValueAt(baris,0).toString());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "DATA AMPLANG SUDAH DIHAPUS!!!");
                table();
            } else {
                JOptionPane.showMessageDialog(null, "DATA TIDAK JADI DIHAPUS!!!");
                table();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int baris = tabelAmplang.getSelectedRow();
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaplikasiamplang", "root", "");
                String sql = "UPDATE tbamplang SET nama=?, jenis=?, ukuran=?, jumlah=?, harga=? WHERE no=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, txtNama.getText());
                String jenis = "";
                boolean isValidSelection = false;
                if (jRadioButton1.isSelected()) {
                   jenis = "Tenggiri";
                   isValidSelection = true;
                } else if (jRadioButton2.isSelected()) {
                   jenis = "Haruan";
                   isValidSelection = true;
                } else if (jRadioButton3.isSelected()) {
                   jenis = "Belida";
                   isValidSelection = true;
                } else {
                   JOptionPane.showMessageDialog(this,
                       "jenis tidak valid, pilih jenis!",
                       "Gagal", JOptionPane.ERROR_MESSAGE);
                }
                pst.setString(2, jenis);
                pst.setString(3, cbUkuran.getSelectedItem().toString());
                pst.setString(4, txtJumlah.getText());
                pst.setString(5, txtHarga.getText());
                pst.setString(6, tabelAmplang.getValueAt(baris,0).toString());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "DATA AMPLANG SUDAH DIUPDATE");
                table();
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariMouseClicked

    }//GEN-LAST:event_txtCariMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseClicked
        String keyword = txtCari.getText();
        DefaultTableModel tbl  = (DefaultTableModel) tabelAmplang.getModel();
        tabelAmplang.setRowHeight(40);
        tabelAmplang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TableColumnModel model_tabel = tabelAmplang.getColumnModel();
        TableColumn column = model_tabel.getColumn(0);
        TableColumn column_5 = model_tabel.getColumn(5);        
        tbl.setRowCount(0);        
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/dbaplikasiamplang", "root", "");
            // membuat statement dan mengirimkan query ke database
            String sql = "SELECT * FROM tbamplang WHERE nama LIKE '%" + keyword + "%'";
            PreparedStatement statement = conn.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            // mengisi data dari ResultSet ke dalam model
            while(rs.next()) {
                String no = Integer.toString(rs.getInt("no"));
                String namaAmplang = rs.getString("nama");
                String jenis = rs.getString("jenis");
                String ukuran = rs.getString("ukuran");
                String jumlah = rs.getString("jumlah");
                String harga = Double.toString(rs.getDouble("harga"));
                tbl.addRow(new Object []{no, namaAmplang, jenis, ukuran, jumlah, harga});
                tabelAmplang.setModel(tbl);
            }
            conn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "There is an error : " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCariMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbUkuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelAmplang;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
